theme = "base16_default"

[editor]
line-number = "relative"
mouse = false
shell = ["bash", "-c"]

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["position", "spacer", "file-type"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = false

[keys.normal]
"space" = { c = ":sh cargo run"} 